concourse/docker-image-resource

- README.md
- assets/common.bash
- assets/in
- assets/out
This change, together with `FROM my-repository:5000/my-base-image` approach and
```
source:
extra_args: --insecure-registry 192.168.59.103:5000
```
solves #4 issue.
> Added support for extra_args during docker daemon start.

- README.md
- assets/out
Buildpacks generates a rootfs.tar.gz for CF rootfses. We then need to push this tarball to Dockerhub.
The `docker load` command does not support loading tarballs that were exported via `docker export`. It only supports those saved via `docker save`. This PR adds support for importing tarballs generated by `docker export` to be pushed to Dockerhub.
> Support `docker import` for pushing exported rootfs

- assets/check
This will allow to specify repositories in private registries:
```
- name: rabbit.docker
type: docker-image
source:
repository: docker.mo.sap.corp/concourse/rabbit
```
If the registry host is omitted it will fallback to the default docker.io registy.
> Accept repositories from a private registries

- README.md
This field was left out of the example, even though it is required.
> Fix example config in README.md to include source repository

- assets/out
`docker save` will store the tag name that the saved image was from, and `docker load` will restore it.  If it is the same as the desired tag name, `docker tag` will refuse to re-tag the image to the desired tag and fail.
> Force set tags when loading from files because they can be the same

- cmd/check/main.go
This is a fix for #33
This fixes discovering digests on docker distribution >= 2.3.1 by explicitly requesting schema v2 manifests.
Before distribution 2.3.1 the v2 schema 1 manifests contained the schema 2 digest by accident which was fixed with this commit https://github.com/docker/distribution/commit/d7eb5d118a6a14a6f320062296b1808506c35241.
docker pull (at least on recent versions of docker) only works with v2 digest. So this only worked by accident until it was fixed.
> Explicitly request v2 schema 2 manifests

- cmd/check/main.go
As described in issue #40 a Docker registry in Artifactory 4.4.2 (and probably earlier) responds to the manifest request with content-type `application/json`, which results in a 406 return code. This change adds that content-type to the Accept header. Have tested against our Artifactory registry and also against the public Docker hub and both work.
> Added application/json to manifestRequest Accept header

- README.md
- assets/common.sh
- assets/in
- assets/out
- cmd/check/main.go
- cmd/check/models.go
Adding a property to the source to allow use of a registry mirror on the docker daemon.
Adds the --registry-mirror argument to the docker daemon for the  in and out scripts and  changes the registry host to the registry mirror in the check.
> Adding registry mirror parameter on source

- assets/common.sh
The `registry` variable used in the loop in `common.sh/start_docker` will override the one in the outer scope (e.g. in [`out`](https://github.com/concourse/docker-image-resource/blob/master/assets/in#L56))
Most of the time this doesn't matter as they are the same.  However it is possible, as in my case, that the `insecure_registries` lists a private registry containing the base image which differs from the registry being published too, so the values will be different.
> Use a local "registry" variable in start_docker

- README.md
- assets/out
This pull request allows specifying a different tag to pull for caching. This way caching can be used even when a new tag is built. For our case we use a new image tag for each git commit. As it is right now, we can't use `cache` in this case. With this pull request we'd be able to use `tag_as_latest: True` and `cache_tag: latest` to enable caching and cut down build times.
> Cache tag parameter

- README.md
- assets/in
This can help us pass context via "LABEL" and other image information natively supported by the docker image.
> Request: Output the docker inspect information from the image

- assets/common.sh
This lets the docker daemon adopt the mtu set on the outer gardian container via `--garden-mtu=` flag.
Fixes #67
> Set docker daemon --mtu flag

- assets/out
Conditionally adds url from Dockerfile to auths per
awslabs/amazon-ecr-credential-helper#9
A `fly execute -c ci/build.yml --output=out/ && docker build out` version
is pushed to https://hub.docker.com/r/donaldguy/concourse-docker-image-resource
and I tested it on my server
> Allow use of ECR urls in FROM

- cmd/check/main.go
On the docker hub the format is fixed at user/repo but in a private registry you can have `my.repo/group/project/image/subimage` fine.
Fixes #81
> Don't assume anything about the image name on private registries.

- cmd/check/main.go
- cmd/check/models.go
If a tag is specified in yaml like:
```
tag: 2
```
It will get turned into json as `{"tag": 2}`. We could try to fix this at the Go yaml->json level, but I think it's harder than just handling either here. json.Number can handle a thing that is totally a string (`{"tag": "foo"}`), or just sorta a string (`{"tag": 2.5}`).
I encountered this when trying to use the Ruby 2.1 docker image. I had to add quotes around the tag in my pipeline. I got this very confusing error in my task that was using that docker image:
```
resource script '/opt/resource/check []' failed: exit status 1
stderr:
failed to read request: json: cannot unmarshal number into Go value of type string
```
> Treat Source.Tag as a json.Number

- cmd/check/main.go
We should add a timeout in case pingClient fails, otherwise check will just hang and we will never see the error that caused pingClient to fail.
> Added timeout to pingClient.

- assets/out
- tests/fixtures/bin/docker
- tests/out_test.go
This change properly escapes multiline/complex build arg values when calling `docker build`.
Fixes #158, Fixes #79 
*Note*: We couldn't get the tests to run on OSX. We think the `README.md` needs some updating?
Signed-off-by: Lyle Franklin <lfranklin@pivotal.io>
> Double quote build args to support complex values

- README.md
- assets/common.sh
In the event that SKIP_PRIVILEGED is not set and common.sh is sourced
into a file that has `set -u`, it will error:
```
/opt/resource/common.sh: line 47: SKIP_PRIVILEGED: unbound variable
```
I discovered this while trying to build HEAD of docker-image-resource to
be used as a resource_type. The image built but put was failing with the
above error.
The test used will substitute parameter if it is set and not null,
otherwise set null if the parameter is null, otherwise use "" (null) if
it is unset. See http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02 for a table explaining each.
> Add default to SKIP_PRIVILEGED

- assets/out
- tests/out_test.go
Solves issue #131
Concourse supports passing the http_proxy family of environment variables from the workers to the containers running on them: concourse/concourse#319
These environment variables do not propagate, however, when building a docker image with docker-image-resource which leaves a pretty large blind spot. This PR fixes that by adding all present proxy setting environment variables as build arguments.
You may see this warning during docker image build if you have proxy environment variable enabled:
`[Warning] One or more build-args [http_proxy https_proxy] were not consumed`
This is because Docker fails to detect that these arguments are being used (even when they're used). It's thankfully harmless.
> Propagate worker proxy settings when building docker images

- assets/out
- tests/fixtures/ecr/Dockerfile.multi-ecr
- tests/out_test.go
If a multi-part build contains more than one ECR base image then the build fails with an `invalid reference format` error. This is due to the docker pull for ECR trying to fetch both images in one command `docker pull <image1> <image2>`.
This PR performs a `docker pull` for each ECR image found in the Dockerfile.
> Allow multiple ECR images in dockerfile

- README.md
- assets/out
- tests/out_test.go
Docker supports [multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/#use-multi-stage-builds), which allows for creating smaller resulting Docker images by throwing away intermediate containers.
Using multi-stage builds typically results in two or more `FROM` statements in the `Dockerfile`, so it makes sense to want to load multiple images to speed up building images.
I've added this as `load_bases` for simplicity, but I realize there's history with `load` and `load_base` as evidenced by `assets/out`.
I'm all for using a different key; when one is settled on I'll update the README as well.
Sample configuration:
```
- put: deploy-image
params:
build: workspace
dockerfile: workspace/Dockerfile
load_bases:
- golang
- debian
```
> Add support for multiple load bases

- assets/common.sh
This appears to now be necessary to start docker; otherwise we get a confusing `cgroups: cannot found cgroup mount destination: unknown` error the first time a docker step involves running executables.
Fixes #174
> docker: force create systemd cgroup

- assets/common.sh
While waiting for docker to come up, sometimes this can take awhile,
especially when docker will never come up and something else will
timeout. Having the echo within the loop can leave you with many, many
lines of repeated stdout. This is unecessary output that provides no
value and can cause issues when builds fail with many 10s of thousands of
outputted lines and the browser attempts to load the build output.
> Avoid indefinitely echoing while waiting for docker

- Dockerfile
The ADD command in the Dockerfile extracts a local tar archive
if its recognized as a gzip, bzip2 or xz.
But in this case the xz library is missing form the standard alpine:edge image.
> Installs the xz library into the resource image.

- README.md
It is inaccurate to say that build args will not persist in the final image. They are visible with `docker history` and `docker inspect`. The old description may cause someone to expose secrets.
As soon as possible, we should upgrade to docker 18.09 to support `--secret` - a way to securely pass credentials into the build context.
https://github.com/docker/cli/pull/1288
> Improve build_args description

- assets/in
The 'in' script performs no Docker operations when `skip_download` is set to true, so it does not make sense to start dockerd in that case. Considering that one usually sets `skip_download: true` to speed up the implicit "get" of the "put" operation, i think it's a meaningful optimization.
> do not start dockerd in 'in' script if skip_download is set to true

- cmd/check/main.go
- tests/check_test.go
Fixes https://github.com/concourse/concourse/issues/980
When a user of Concourse accidentally puts a bad image name, we (the maintainers) of Concourse gets questions like "why is my pipeline broken? I did not change anything" since its not clear that the image they specified is bad.
```
- name: build
- task: build
config:
platform: linux
image_resource:
type: docker-image
source:
repository: Ubuntu is an ancient african word, meaning I can't configure Debian
tag: latest
.. ... ..
```
instead of seeing in the UI
```
error: check failed with exit status '1':
failed to fetch digest: 401 Unauthorized
```
the user would now see
```
error: check failed with exit status '1':
failed to fetch digest for image 'Ubuntu is an ancient african word, meaning I can't configure Debian:latest': 401 …
```
> Print a nicer error message when the image cannot be found

- assets/common.sh
- assets/out
- tests/fixtures/bin/docker
- tests/out_test.go
##Problem
Builds would fail if the cached pull failed, this caused problems when first running an automated build and no image exists in the repository.
Stop `--cache-from` being added if the docker pull fails
Added tests for basic caching parameter and what happens if it fails to pull
Fixes #222
> Allow Build to continue if cache pull fails

- dockerfiles/alpine/Dockerfile
There should be no differences in the `builder` stage between the ubuntu and
alpine docker images. The only difference should be in the resource stage
which encapsulates all of the distro specific differences.
Fixes #267
> bug: issue 267 alpine docker build fails

- README.md
Client cert config does not require a port number.
Fixes #280
> Update Client Cert Config

- README.md
I'm hosting concourse with a private registry which requires a `docker login` within the same docker-compose file. The service for my registry was called `harbor`. 
I've stumbled upon this behavior as i wasn't able to put a docker image resource to this registry as it always tried to login to docker hub. 
This behavior origins in the `private_registry()` function in `common.sh` https://github.com/concourse/docker-image-resource/blob/f7dfbc17c2f633eb165e1fc5b7363b582af6a7e3/assets/common.sh#L124-L135 as it checks if the first part of the docker image name contains a `.` to mark it as private e.g. `registry.example.com`. However when you use the name `registry` in the docker-compose file for your services hostname it will break.
As is don't want to change the default behavior and have no …
> added note in readme regarding private registry hostnames

- README.md
- cmd/check/main.go
- tests/check_test.go
This addresses issue #305 
I'm also happy to ~write tests~ and/or provider further tweaks, but thought it might be worth getting some early feedback before doing so. Thanks!
Update: I went ahead and wrote a few tests :)
> Prevent 'registry_mirror' from overwriting the hostname in a 'repository' containing a registry host name

- README.md
- assets/common.sh
I improved the checks for the detection if the registry is private or dockerhub.
I check if either "." or ":" (or both) are present in the address.
I tested the relevant functions with this little script that reflects all changes i made in this PR. I also modified the Readme according to this new behavior.
```bash
#!/bin/bash
declare -a registries=("registry"
"registry/foo"
"registry:5000"
"registry:5000/foo"
"registry.local"
"registry.local/foo"
"registry.local:5000"
"registry.local:5000/foo")
extract_registry() {
local repository="${1}"
echo "${repository}" | cut -d/ -f1
}
extract_repository() {
local long_repository="${1}"
echo "${long_repository}" | cut -d/ -f2-
}
private_registry() {
local repository="${1}"
local registry="$(extract_registry "${repository}")"
if echo "${registry}" | …
```
> Better check for private registry or dockerhub

- cmd/check/main.go
Fixes #311
This changes the check flow to call headDigest instead of fetchDigest directly.
If headDigest fails to get the digest it will fall back to using fetchDigest.
Tested in the following scenarios:
- Upstream to dockerhub with library and user repos
- Against private nexus registry with pull-through cache both directly and with registry_mirror
- Against the repo called out in #307 which spawned the initial change.
This fix is required for us to upgrade to 6.7.x as the nexus pull-through-cache works with HEAD requests and not GET requests for check
(problem for another day) as well as important for the Dockerhub ratelimiting on Nov 2
> Fix Check implementation to properly use HEAD requests

- assets/common.sh
In short, forcefully creating systemd cgroups on systems without systemd makes Docker fail with same error as in https://github.com/concourse/docker-image-resource/commit/264b3718b5b85d850c208159fe2dd364620a83d1  - `docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.` just this time it hapens on host system.
( Previously reported as https://github.com/vito/oci-build-task/issues/27 )
To make things more fun, some systems have cgroups auto-cleaning, so after container is destroyed everything will work again.
This PR tries to fix this behavior on OpenRC systems, my knowledge about cgroups is shallow but it seems to not break anything.
How to reproduce problem:
Vagrantfile:
```
$script = <<-SCRIPT
apk add docker
/etc/init.d/docker start
SCRIPT …
```
> Skip Systemd cgroup creation on systems with OpenRC

- assets/common.sh
This PR outputs the contents of the log file to console in the event docker fails to start. A lot of my users are having issues with docker starting, and troubleshooting is difficult without this information. The containers have often been garbage collected by the time I come to investigate.
Signed-off-by: Tom Bartlett <tom.bartlett@spire.com>
> Output contents of log file on error

- README.md
- assets/out
For more info, please see https://docs.docker.com/develop/develop-images/build_enhancements/
> add docker buildkit support

- assets/common.sh
- assets/out
When running within docker-in-docker context, and more specifically in this resource, and only when buildkit is enabled, there is an issue with the aws `ecr_login` authenticator plugin of docker.  Specifically, it gets confused and tries to authenticate attempts to fetch from non-ECR registries.  It then gives up errors such as "xxx... is not a valid repository URI for Amazon Elastic Container Registry" for layers from say, docker hub, and the `docker build` fails.
Fortunately, there is already code in `assets/out:242` which does an explicit pull for base images from ECR, if any, which means, the `docker build` step doesn't actually need the `ecr_login` plugin.
This PR removes the `ecr_login` plugin while calling `docker build`, and then puts it back immediately after.
I have tested that …
> Fix broken interaction of BUILDKIT and docker ecr_login plugin

- assets/common.sh
On cgroup v2 systems (like fedora v31+) the cgroup sanitization will fail with a error message like
```
mount: /sys/fs/cgroup/cpuset: cgroup already mounted on /sys/fs/cgroup.
```
(The exact mountpoint probably depends on the available cgroups).
This simply bails out, as this mounting is no longer necessary with cgroup v2.
This was tested on a cgroup v2 system using a containerd runner.
> Skip cgroup sanitization for cgroup v2

- assets/common.sh
When we are building and pushing a docker image via the resource we faced login error issue. Up on investigation it is something related to this [ISSUE](https://github.com/docker/hub-feedback/issues/1250). As per the issue, it says login fails for 2 reasons. 1. Due to password having special chars and 2. login is happening V2 [this gets solved via logout and login again].
As per the analysis I have done, looks like first [login](https://github.com/concourse/docker-image-resource/blob/master/assets/out#L55) is happening/happened via V1 and during second [login](https://github.com/concourse/docker-image-resource/blob/master/assets/out#L250) it tried via V2 and failure is seen.
sometime I am seeing the issue while performing get after successful PUT or at first login of the PUT. 
Though the …
> fixing docker login issue due 2 logins we are performing during put

- README.md
- assets/common.sh
- assets/out
This PR adds a new optional config parameter `additional_private_registries`, which allows a pipeline to authenticate to multiple docker registries.  
This is useful when trying to build a Dockerfile that depends on an image that is only available from a private registry, which is separate from the registry where the resulting docker image will be published.  For example, pulling from a private 3rd party docker registry and publishing to an internal docker registry, or transitioning to a new docker registry while still allowing pulls from an old docker registry.  
I have built this resource locally and tested it with our Concourse, per the instructions in the README.  When specifying additional registries, the resource successfully authenticated to all of them, and published the image as …
> add support for authenticating to additional docker registries

- assets/out
- tests/out_test.go
The `additional_private_registries` parameter (from this PR: https://github.com/concourse/docker-image-resource/pull/345)  is broken when when this resource type is built using the alpine linux Dockerfile, but it works as intended using the ubuntu Dockerfile.  
The reason for this is because alpine's `base64` doesn't accept `--decode`.  Both ubuntu and alpine understand `-d`, so let's change it to pass that instead.  
Crucially, the docker-image resource type bundled with concourse is built from the alpine Dockerfile, so `additional_private_registries` will not work until this is merged, released, and bundled into a new version of concourse.
> fix additional_private_registries on alpine

- README.md
- assets/out
- tests/out_test.go
This adds the ssh identity support to the concourse yaml
Original work: https://github.com/concourse/docker-image-resource/pull/331
Tests pass locally however I cannot determine why the concourse-ci/status failed
> Add secrets support
